name: organization-secrets

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production 
    env:
      TEST_VARIABLE: ${{ vars.TEST_VARIABLE }} 
    steps:
      - uses: actions/checkout@v4

      - name: One-line script
        run: echo Hello!

      - name: Print environment secret
        run: echo "Env secret is:${{ secrets.PROD_API_KEY }}"  # ðŸ‘ˆ environment secret

      - name: Print environment variable
        run: echo "TEST_VARIABLE is:$TEST_VARIABLE"

      - name: Print org secret
        run: echo "Org secret is:${{ secrets.DB_CREDENTIALS }}"

